### ISSUE TITLE
Migrate from Python 2 to 3

### ISSUE THREAD

**Issue by sadielbartholomew** [ES-DOC/esdoc-documentation-ws#12]
Our web services are broken at numerous endpoints, ultimately due to API requests failing on Python 2 (some libararies such as Apache Arrow used in the stack no longer support Python 2 at all, and rewinding to older versions causes dependency consistency hell). So we should migrate ASAP.

I will get this done, at least for a branch, today.

**Comment by davidhassell** [comment]
Great.

**Comment by sadielbartholomew** [comment]
Done as of yesterday in the branch `python2to3`(see https://github.com/ES-DOC/esdoc-documentation-ws/compare/master...python2to3) which I have pushed here. I won't open a PR with that and merge until I have got things working on the server-side, in case tweaks need to be made to the migration that should be captured in the PR.

**Comment by sadielbartholomew** [comment]
Note to self: `2to3` adds whitespace as tabs (:confused:), so add a commit to mass-convert to whitespace pre-merge.
